/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visualização;

import Modelagem.Guia;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MMRibeir
 */
public class FCadastrarGuia extends javax.swing.JInternalFrame {

    /**
     * Creates new form FCadastrarGuia
     */
    public FCadastrarGuia() {
        initComponents();
        setSize(270,580);
    }
    
    Guia gui = new Guia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LSenha = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        LEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnSalvar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        ImagemFundo = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        LSenha.setBackground(new java.awt.Color(255, 255, 255));
        LSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LSenha.setForeground(new java.awt.Color(255, 255, 255));
        LSenha.setText("Senha");
        getContentPane().add(LSenha);
        LSenha.setBounds(40, 320, 40, 20);

        LNome.setBackground(new java.awt.Color(255, 255, 255));
        LNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LNome.setForeground(new java.awt.Color(255, 255, 255));
        LNome.setText("Nome");
        getContentPane().add(LNome);
        LNome.setBounds(40, 80, 50, 20);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 370, 170, 20);

        txtNome.setBackground(new java.awt.Color(0, 20, 39));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        getContentPane().add(txtNome);
        txtNome.setBounds(40, 110, 150, 20);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(40, 130, 170, 20);

        LSobrenome.setBackground(new java.awt.Color(255, 255, 255));
        LSobrenome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        LSobrenome.setText("Sobrenome");
        getContentPane().add(LSobrenome);
        LSobrenome.setBounds(40, 160, 80, 20);

        txtSobrenome.setBackground(new java.awt.Color(0, 20, 39));
        txtSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        txtSobrenome.setBorder(null);
        getContentPane().add(txtSobrenome);
        txtSobrenome.setBounds(40, 190, 170, 20);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(40, 210, 170, 20);

        LEmail.setBackground(new java.awt.Color(255, 255, 255));
        LEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email");
        getContentPane().add(LEmail);
        LEmail.setBounds(40, 240, 40, 20);

        txtEmail.setBackground(new java.awt.Color(0, 20, 39));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(40, 270, 170, 20);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(40, 290, 170, 20);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(60, 430, 140, 30);

        txtSenha.setBackground(new java.awt.Color(0, 20, 39));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(40, 350, 170, 16);

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualização/Images/FundoGuia.png"))); // NOI18N
        getContentPane().add(ImagemFundo);
        ImagemFundo.setBounds(1, 0, 269, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        
        gui.setNome(txtNome.getText());
        gui.setSobrenome(txtSobrenome.getText());
        gui.setEmail(txtEmail.getText());
        gui.setSenha(txtSenha.getText());
        gui.gravar();
                
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LSobrenome;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
