/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visualização;

import javax.swing.JFrame;

/**
 *
 * @author mateu
 */
public class FMenu extends javax.swing.JFrame {

    /**
     * Creates new form FMenu
     */
    public FMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemTurista = new javax.swing.JMenuItem();
        mItemGuia = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItemVerTrilhas = new javax.swing.JMenuItem();
        mItemVerGuias = new javax.swing.JMenu();
        mItemDeletarGuias = new javax.swing.JMenuItem();
        Dados = new javax.swing.JMenu();
        mItemDadosTuristas = new javax.swing.JMenuItem();
        mItemDadosGuias = new javax.swing.JMenuItem();
        mItemDadosTrilhas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualização/Images/funod.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastrar");

        mItemTurista.setText("Turista");
        mItemTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemTuristaActionPerformed(evt);
            }
        });
        jMenu1.add(mItemTurista);

        mItemGuia.setText("Guia");
        mItemGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemGuiaActionPerformed(evt);
            }
        });
        jMenu1.add(mItemGuia);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Trilhas");

        mItemVerTrilhas.setText("Ver trilhas");
        mItemVerTrilhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVerTrilhasActionPerformed(evt);
            }
        });
        jMenu2.add(mItemVerTrilhas);

        jMenuBar1.add(jMenu2);

        mItemVerGuias.setText("Guias");

        mItemDeletarGuias.setText("Deletar guias");
        mItemVerGuias.add(mItemDeletarGuias);

        jMenuBar1.add(mItemVerGuias);

        Dados.setText("Dados");

        mItemDadosTuristas.setText("Turistas");
        mItemDadosTuristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDadosTuristasActionPerformed(evt);
            }
        });
        Dados.add(mItemDadosTuristas);

        mItemDadosGuias.setText("Guias");
        mItemDadosGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDadosGuiasActionPerformed(evt);
            }
        });
        Dados.add(mItemDadosGuias);

        mItemDadosTrilhas.setText("Trilhas");
        mItemDadosTrilhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDadosTrilhasActionPerformed(evt);
            }
        });
        Dados.add(mItemDadosTrilhas);

        jMenuBar1.add(Dados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemTuristaActionPerformed
        // TODO add your handling code here:
        FCadastrarTurista turis = new FCadastrarTurista();
        jDesktopPane1.add(turis);
        turis.setVisible(true);
    }//GEN-LAST:event_mItemTuristaActionPerformed

    private void mItemVerTrilhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVerTrilhasActionPerformed
        // TODO add your handling code here:
        FTrilhas tri = new FTrilhas();
        jDesktopPane1.add(tri);
        tri.setVisible(true);
        
        
    }//GEN-LAST:event_mItemVerTrilhasActionPerformed

    private void mItemGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemGuiaActionPerformed
        // TODO add your handling code here:
        FCadastrarGuia guia = new FCadastrarGuia();
        jDesktopPane1.add(guia);
        guia.setVisible(true);
    }//GEN-LAST:event_mItemGuiaActionPerformed

    private void mItemDadosTrilhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDadosTrilhasActionPerformed
        // TODO add your handling code here:
        FDadosTrilhas dTril = new FDadosTrilhas();
        jDesktopPane1.add(dTril);
        dTril.setVisible(true);
    }//GEN-LAST:event_mItemDadosTrilhasActionPerformed

    private void mItemDadosGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDadosGuiasActionPerformed
        // TODO add your handling code here:
        FDadosGuias dGuia = new FDadosGuias();
        jDesktopPane1.add(dGuia);
        dGuia.setVisible(true);
    }//GEN-LAST:event_mItemDadosGuiasActionPerformed

    private void mItemDadosTuristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDadosTuristasActionPerformed
        // TODO add your handling code here:
        FDadosTuristas dTuri = new FDadosTuristas();
        jDesktopPane1.add(dTuri);
        dTuri.setVisible(true);
    }//GEN-LAST:event_mItemDadosTuristasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Dados;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem mItemDadosGuias;
    private javax.swing.JMenuItem mItemDadosTrilhas;
    private javax.swing.JMenuItem mItemDadosTuristas;
    private javax.swing.JMenuItem mItemDeletarGuias;
    private javax.swing.JMenuItem mItemGuia;
    private javax.swing.JMenuItem mItemTurista;
    private javax.swing.JMenu mItemVerGuias;
    private javax.swing.JMenuItem mItemVerTrilhas;
    // End of variables declaration//GEN-END:variables
}
